// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: ssov2/ssov2.proto

package ssov2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNewUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RegisterNewUserReq) Reset() {
	*x = RegisterNewUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssov2_ssov2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewUserReq) ProtoMessage() {}

func (x *RegisterNewUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_ssov2_ssov2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewUserReq.ProtoReflect.Descriptor instead.
func (*RegisterNewUserReq) Descriptor() ([]byte, []int) {
	return file_ssov2_ssov2_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNewUserReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterNewUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterNewUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterNewUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RegisterNewUserResp) Reset() {
	*x = RegisterNewUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssov2_ssov2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterNewUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNewUserResp) ProtoMessage() {}

func (x *RegisterNewUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_ssov2_ssov2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNewUserResp.ProtoReflect.Descriptor instead.
func (*RegisterNewUserResp) Descriptor() ([]byte, []int) {
	return file_ssov2_ssov2_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNewUserResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssov2_ssov2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_ssov2_ssov2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_ssov2_ssov2_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ssov2_ssov2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_ssov2_ssov2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_ssov2_ssov2_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_ssov2_ssov2_proto protoreflect.FileDescriptor

var file_ssov2_ssov2_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x73, 0x6f, 0x76, 0x32, 0x2f, 0x73, 0x73, 0x6f, 0x76, 0x32, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x73, 0x6f, 0x76, 0x32, 0x22, 0x5c, 0x0a, 0x12, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2e, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x7c, 0x0a, 0x04, 0x41, 0x75, 0x74,
	0x68, 0x12, 0x48, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x73, 0x73, 0x6f, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x1a, 0x2e, 0x73, 0x73, 0x6f, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0f, 0x2e, 0x73, 0x73, 0x6f, 0x76, 0x32, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x73, 0x73, 0x6f, 0x76, 0x32, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x73, 0x73, 0x6f, 0x76, 0x32,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ssov2_ssov2_proto_rawDescOnce sync.Once
	file_ssov2_ssov2_proto_rawDescData = file_ssov2_ssov2_proto_rawDesc
)

func file_ssov2_ssov2_proto_rawDescGZIP() []byte {
	file_ssov2_ssov2_proto_rawDescOnce.Do(func() {
		file_ssov2_ssov2_proto_rawDescData = protoimpl.X.CompressGZIP(file_ssov2_ssov2_proto_rawDescData)
	})
	return file_ssov2_ssov2_proto_rawDescData
}

var file_ssov2_ssov2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ssov2_ssov2_proto_goTypes = []any{
	(*RegisterNewUserReq)(nil),  // 0: ssov2.RegisterNewUserReq
	(*RegisterNewUserResp)(nil), // 1: ssov2.RegisterNewUserResp
	(*LoginReq)(nil),            // 2: ssov2.LoginReq
	(*LoginResp)(nil),           // 3: ssov2.LoginResp
}
var file_ssov2_ssov2_proto_depIdxs = []int32{
	0, // 0: ssov2.Auth.RegisterNewUser:input_type -> ssov2.RegisterNewUserReq
	2, // 1: ssov2.Auth.Login:input_type -> ssov2.LoginReq
	1, // 2: ssov2.Auth.RegisterNewUser:output_type -> ssov2.RegisterNewUserResp
	3, // 3: ssov2.Auth.Login:output_type -> ssov2.LoginResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ssov2_ssov2_proto_init() }
func file_ssov2_ssov2_proto_init() {
	if File_ssov2_ssov2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ssov2_ssov2_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterNewUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssov2_ssov2_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterNewUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssov2_ssov2_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ssov2_ssov2_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ssov2_ssov2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ssov2_ssov2_proto_goTypes,
		DependencyIndexes: file_ssov2_ssov2_proto_depIdxs,
		MessageInfos:      file_ssov2_ssov2_proto_msgTypes,
	}.Build()
	File_ssov2_ssov2_proto = out.File
	file_ssov2_ssov2_proto_rawDesc = nil
	file_ssov2_ssov2_proto_goTypes = nil
	file_ssov2_ssov2_proto_depIdxs = nil
}
